alter table p_coupon_policy drop constraint if exists p_coupon_policy_fk_coupon;
drop table p_coupon cascade;
drop table p_coupon_policy cascade;
drop table p_user_coupon cascade;
drop sequence p_user_coupon_seq;
create sequence p_user_coupon_seq start with 1 increment by 50;

create table p_coupon (
                          allow_duplicate boolean not null,
                          count integer not null,
                          issued_count integer not null,
                          valid_days integer,
                          created_at timestamp(6),
                          created_by bigint,
                          deleted_at timestamp(6),
                          deleted_by bigint,
                          end_at timestamp(6) not null,
                          id bigint generated by default as identity,
                          start_at timestamp(6) not null,
                          updated_at timestamp(6),
                          updated_by bigint,
                          coupon_uuid varchar(100) not null unique,
                          name varchar(200) not null,
                          label varchar(255) not null check (label in ('GENERAL','PROMOTION','HOT')),
                          type varchar(255) not null check (type in ('FIXED_DISCOUNT','PERCENT_DISCOUNT')),
                          primary key (id)
);
create table p_coupon_policy (
                                 amount integer,
                                 max_discount_amount integer,
                                 min_purchase_amount integer not null,
                                 percent integer,
                                 created_at timestamp(6),
                                 created_by bigint,
                                 deleted_at timestamp(6),
                                 deleted_by bigint,
                                 id bigint generated by default as identity,
                                 updated_at timestamp(6),
                                 updated_by bigint,
                                 coupon_uuid varchar(100) unique,
                                 discount_policy_uuid varchar(100) not null unique,
                                 primary key (id)
);
create table p_user_coupon (
                               created_at timestamp(6),
                               created_by bigint,
                               deleted_at timestamp(6),
                               deleted_by bigint,
                               expires_at timestamp(6) not null,
                               id bigint not null,
                               preempt_at timestamp(6),
                               updated_at timestamp(6),
                               updated_by bigint,
                               used_at timestamp(6),
                               user_id bigint not null,
                               coupon_uuid varchar(100) not null,
                               reservation_uuid varchar(100),
                               user_coupon_uuid varchar(100) not null,
                               name varchar(200) not null,
                               status varchar(255) not null check (status in ('ISSUED','PREEMPT','COMMIT','ROLLBACK')),
                               primary key (id)
);
alter table if exists p_coupon_policy
    add constraint p_coupon_policy_fk_coupon
    foreign key (coupon_uuid)
    references p_coupon (coupon_uuid);
ALTER TABLE p_user_coupon
    ALTER COLUMN id SET DEFAULT nextval('p_user_coupon_seq');