spring:
  application:
    name: review
  datasource:
    url: ${REVIEW_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/