server:
  port: 8081

spring:
  config:
    import: optional:file:.env.user[.properties]
  application:
    name: user
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${PROD_EUREKA_SERVICE_URL}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: false
    non-secure-port: 80

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${PROD_ZIPKIN_ENDPOINT}

