### 대기 정보 조회
GET localhost:8086/internal/v1/waitings/00000000-0000-0000-0000-000000000001
Content-Type: application/json

### 대기 요청 생성
POST localhost:8086/api/v1/waiting-requests
Content-Type: application/json
X-User-Id: 2
X-User-Role: CUSTOMER

{
  "dailyWaitingUuid":"00000000-0000-0000-0000-000000000001",
  "phone":"01000000000",
  "slackId":"slackId@example.com",
  "seatSize": 4
}

> {%
  const location = response.headers.valueOf("Location")
  const match = location.match(/[0-9a-fA-F\-]{36}$/)

  if (match) {
    client.global.set("waitingRequestUuid", match[0]);
  }
%}

### 대기 입장 요청  # 임시
POST localhost:8086/admin/v1/waiting-requests/{{waitingRequestUuid}}/entrance
Content-Type: application/json
X-User-Id: 3
X-User-Role: STAFF

### 대기 요청 목록 조회 # 임시
PATCH localhost:8086/admin/v1/waiting-requests?dailyWaitingUuid=00000000-0000-0000-0000-000000000001
Content-Type: application/json
X-User-Id: 3
X-User-Role: STAFF

### 대기 요청 조회 admin # 임시
GET localhost:8086/admin/v1/waiting-requests/{{waitingRequestUuid}}
Content-Type: application/json
X-User-Id: 3
X-User-Role: STAFF

### 대기 요청 조회 
GET localhost:8086/api/v1/waiting-requests/{{waitingRequestUuid}}?phone=01000000000
Content-Type: application/json

### 대기 연기 요청
PATCH localhost:8086/api/v1/waiting-requests/{{waitingRequestUuid}}/postpone?phone=01000000000
Content-Type: application/json