services:
  gateway:
    container_name: hidle-gateway
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:gateway
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod