###
POST http://localhost:8089/admin/v1/notifications
Content-Type: application/json

{
  "notificationType": "CONFIRM_OWNER",
  "message": "예약이 확정되었습니다.",
  "status": "PENDING",
  "notificationMethod": "SLACK",
  "scheduledTime": "2025-04-08T17:00:00"
}
