###
POST http://localhost:8081/api/v1/users/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@test",
  "phone": "123",
  "password": "1234",
  "role": "MASTER"
}

###
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
"username": "test",
"password": "1234"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

###
POST http://localhost:8089/admin/v1/notifications
Content-Type: application/json
Authorization: {{access_token}}
X-User-Id: 1
X-User-Role: MASTER

{
  "userId": 1,
  "notificationType": "REMINDER_1HR",
  "customerName": "홍길동",
  "reservationTime": "2025-04-21T18:30:00",
  "restaurantName": "맛있는 식당",
  "status": "PENDING",
  "notificationMethod": "SLACK",
  "scheduledTime": "2025-04-21T02:20:00"
}


### 수정
PUT http://localhost:8089/admin/v1/notifications
Content-Type: application/json
X-User-Id: 1
X-User-Role: MASTER

{
  "userId": 1,
  "notificationType": "REMINDER_1HR",
  "customerName": "홍길동",
  "reservationTime": "2025-04-21T18:30:00",
  "restaurantName": "맛있는 식당",
  "status": "PENDING",
  "notificationMethod": "SLACK",
  "scheduledTime": "2025-04-21T01:40:00"
}

###
GET http://localhost:8080/admin/v1/notifications?userId=1&status=PENDING&notificationMethod=SLACK&isAsc=true&sortBy=scheduledTime&page=0&size=2
Authorization: {{access_token}}

###
GET http://localhost:8089/admin/v1/notifications/test/f42e7a8d-c2e5-4045-ae16-d909296c9854
X-User-Id: 1
X-User-Role: MASTER