spring:
  application:
    name: server

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://table-eat-now-server-blue-env.eba-29ui92w2.ap-northeast-2.elasticbeanstalk.com/eureka/  # Eureka 서버 URL
    register-with-eureka: false  # Eureka 서버에 등록
    fetch-registry: false  # Eureka 서버로부터 레지스트리 정보 가져오기
  instance:
    hostname: table-eat-now-server-blue-env.eba-29ui92w2.ap-northeast-2.elasticbeanstalk.com  # 클라이언트 호스트 이름

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  endpoint:
    health:
      show-details: always