server:
  port: 8089

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification
  datasource:
    url: ${NOTIFICATION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 30
    show-sql: true

eureka:
  client:
    register-with-eureka: true  # Eureka Server에 등록
    fetch-registry: true  # Eureka Server에서 서비스 목록 가져오기
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # 서비스 등록 시 IP 주소 사용