services:
  gateway:
    container_name: hidle-review
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:review
    ports:
      - "80:8087"
    volumes:
      - ./logs:/logs
      - ./.env.review:/app/.env.review
    environment:
      SPRING_PROFILES_ACTIVE: prod