services:
  server:
    container_name: hidle-server
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:server
    ports:
      - "80:8761"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod