###
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@test",
  "phone": "123",
  "password": "1234",
  "role": "MASTER"
}

###
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

###
POST http://localhost:8080/admin/v1/promotions
Content-Type: application/json
Authorization: {{access_token}}

{
  "promotionName": "봄맞이 할인 프로모션",
  "description": "전 메뉴 3000원 할인",
  "startTime": "2025-04-09T00:00:00",
  "endTime": "2025-04-18T00:00:00",
  "discountAmount": 3000,
  "promotionStatus": "READY",
  "promotionType": "COUPON"
}

###
PUT http://localhost:8080/admin/v1/promotions/{{promotionUuid}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "promotionName": "봄맞이 할인 프로모션",
  "description": "전 메뉴 4000원 할인 - 수정",
  "startTime": "2025-04-10T00:00:00",
  "endTime": "2025-04-20T00:00:00",
  "discountAmount": 4000,
  "promotionStatus": "READY",
  "promotionType": "COUPON"
}