###
POST http://localhost:8080/api/v1/users/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@test",
  "phone": "123",
  "password": "1234",
  "role": "MASTER"
}

###
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}
> {%
  client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

###
POST http://localhost:8084/admin/v1/promotions
Content-Type: application/json
X-User-Role: MASTER
X-User-Id: 1
#Authorization: {{access_token}}

{
  "promotionName": "자리 eat now 오픈 프로모션입니다.13",
  "description": "전 메뉴 3000원 할인 쿠폰",
  "startTime": "2025-04-28T23:38:00",
  "endTime": "2025-04-29T00:20:00",
  "discountAmount": 3000,
  "promotionStatus": "READY",
  "promotionType": "COUPON"
}

###
PUT http://localhost:8080/admin/v1/promotions/{{promotionUuid}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "promotionName": "봄맞이 할인 프로모션",
  "description": "전 메뉴 4000원 할인 - 수정",
  "startTime": "2025-04-10T00:00:00",
  "endTime": "2025-04-20T00:00:00",
  "discountAmount": 4000,
  "promotionStatus": "READY",
  "promotionType": "COUPON"
}

###
GET http://localhost:8080/api/v1/promotions?promotionName=할인&description=시즌&startTime=2025-04-11T14:00:00&endTime=2025-04-15T14:00:00&discountAmount=1000&promotionStatus=READY&promotionType=COUPON&isAsc=true&sortBy=startTime&page=0&size=2
Authorization: {{access_token}}

###
DELETE http://localhost:8080/admin/v1/promotions/{{promotionUuid}}
Authorization: {{access_token}}

###
POST http://localhost:8084/internal/v1/promotions
Content-Type: application/json
X-User-Role: MASTER
X-User-Id: 1

{
  "promotionUuids": [
    "4c5f6d32-7390-49be-8d63-7cd6240d8606",
    "30f6689c-fee0-44b7-a057-5193c54fdb1c"
  ],
  "restaurantUuid": "a03e77a7-4f26-4d4f-8412-bb68b2dd1b88"
}


###
POST http://localhost:8084/api/v1/promotions/event/participate
Content-Type: application/json
X-User-Role: MASTER
X-User-Id: 1

{
  "userId": 1,
  "promotionUuid": "5608eb23-78e0-4e00-9681-bf99b58c6aa1",
  "promotionName": "자리 eat now 오픈 프로모션입니다.4"
}

###
GET http://localhost:8084/api/v1/promotions/test
Content-Type: application/json
X-User-Role: MASTER
X-User-Id: 1

{
  "userId": 1,
  "promotionUuid": "11129213-01cd-4bd9-a7ca-ed6b5a195abf",
  "promotionName": "자리 eat now 오픈 프로모션입니다.3"
}