###
POST http://localhost:8084/admin/v1/promotion-restaurants
Content-Type: application/json

{
  "promotionUuid": "7bde88ba-ec55-4d5c-92d9-4de6f8cb14c9",
  "restaurantUuid": "a03e77a7-4f26-4d4f-8412-bb68b2dd1b88"
}