spring:
  application:
    name: reservation
  config:
    import:
      - optional:file:.env.reservation[.properties]
      - classpath:properties/base.yml
      - classpath:properties/config.yml
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/redis.yml
      - classpath:properties/cloud.yml
      - classpath:properties/zipkin.yml
  profiles:
    group:
      local: local
      test: test
      develop: develop
      prod: prod
    active: local