spring:
  application:
    name: coupon
  config:
    import:
      - optional:file:.env.coupon[.properties]
      - classpath:properties/base.yml
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/redis.yml
      - classpath:properties/cloud.yml
      - classpath:properties/kafka.yml
      - classpath:properties/monitoring.yml
  profiles:
    group:
      local: local
      test: test
      develop: develop
      prod: prod
    active: local