spring:
  application:
    name: payment
  config:
    import: optional:file:.env.payment[.properties]
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 30
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://table-eat-now-server-blue-env.eba-29ui92w2.ap-northeast-2.elasticbeanstalk.com/eureka/}

server:
  port: 8088

payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY}
    api-url: ${TOSS_API_URL}
