package table.eat.now.payment.payment.application.event;

public enum EventType {
  RESERVATION_PAYMENT_SUCCEED,
  RESERVATION_PAYMENT_FAILED,
  RESERVATION_PAYMENT_CANCEL_SUCCEED,
  RESERVATION_PAYMENT_CANCEL_FAILED,
  ;
}