services:
  notification:
    container_name: hidle-notification
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:notification
    ports:
      - "80:8089"
    volumes:
      - ./logs:/logs
      - ./.env.notification:/app/.env.notification
    environment:
      SPRING_PROFILES_ACTIVE: prod