# local 환경
spring:
  config.activate.on-profile: local
  cloud:
    config:
      enabled: false

---
# test 환경
spring:
  config.activate.on-profile: test
  cloud:
    config:
      enabled: false

---
# develop 환경
spring:
  config.activate.on-profile: develop
  cloud:
    config:
      enabled: false

---
# prod 환경
spring:
  config.activate.on-profile: prod
  cloud:
    config:
      enabled: true