spring:
  config.activate.on-profile: local
  kafka:
    bootstrap-servers: ${LOCAL_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic:
    reservation:
      # 처리량 확장을 위한 파티션 수
      partitions: 3
      # 고가용성을 위한 복제본 수
      replicas: 3
      # 데이터 손실 방지를 위한 최소 동기화 복제본 수
      min-insync-replicas: 2

---
spring:
  config.activate.on-profile: test
  kafka:
    bootstrap-servers: ${LOCAL_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic:
    reservation:
      partitions: 3
      replicas: 3
      min-insync-replicas: 2

---
spring:
  config.activate.on-profile: develop
  kafka:
    bootstrap-servers: ${DEV_KAFKA_BOOTSTRAP_SERVERS}

kafka:
  topic:
    reservation:
      name: reservation-event
      partitions: 3
      replicas: 3
      min-insync-replicas: 2
