services:
  reservation:
    container_name: hidle-reservation
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:reservation
    ports:
      - "8083:8083"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod