services:
  reservation:
    container_name: hidle-reservation
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:reservation
    ports:
      - "80:8083"
    volumes:
      - ./logs:/logs
      - ./.env.reservation:/app/.env.reservation
    environment:
      SPRING_PROFILES_ACTIVE: prod