services:
  coupon:
    container_name: hidle-coupon
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:waiting
    ports:
      - "8086:8086"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod