# local 환경
spring:
  config.activate.on-profile: local
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8085

---
# test 환경
spring:
  config.activate.on-profile: test
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8085

---
# dev 환경
spring:
  config.activate.on-profile: develop
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8085

---
# prod 환경
spring:
  config.activate.on-profile: prod
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8085