# local 환경
spring:
  config.activate.on-profile: local
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        rewriteBatchedInserts: true
        rewriteBatchedStatements: true # mysql 용
  #      schema: ten
  jdbc:
    batch:
      size: 10000
  sql:
    init:
      mode: always
      #schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/alter.sql # db 시작할때 실행시킬 script

---
# test 환경
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE  # db 주소 고정

---
# dev 환경
spring:
  config.activate.on-profile: develop
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        rewriteBatchedInserts: true
        # rewriteBatchedStatements: true # mysql 용
#      schema: ten