services:
  user:
    container_name: hidle-user
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:user
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod