services:
  user:
    container_name: hidle-user
    image: 390403891668.dkr.ecr.ap-northeast-2.amazonaws.com/hidle-ecr:user
    ports:
      - "80:8081"
    volumes:
      - ./logs:/logs
      - ./.env.user:/app/.env.user
    environment:
      SPRING_PROFILES_ACTIVE: prod