# docker image build and ecr push + Beanstalk server deploy
name: CI/CD
on:
  push:
    branches:
      - feat/#222
    #  - main
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          fetch-depth: 0

      - name: Detect changed modules
        id: set-modules
        run: |
          git fetch origin develop
          changed_files=$(git diff --name-only origin/develop...${{ github.sha }})
          changed_modules=$(echo "$changed_files" | cut -d/ -f1 | sort -u)
          
          if echo "$changed_modules" | grep -q '^common$'; then
            modules=$(find . -maxdepth 1 -type d ! -name '.' | \
              sed 's|^\./||' | \
              grep -Ev '^(\.git|\.github|gradle|ten-private)$' | \
              jq -R -s -c 'split("\n") | map(select(length > 0))')

            echo "modules=$modules" >> "$GITHUB_OUTPUT"
          else
            excluded_dirs="\.github|gradle|ten-private|common|config"
            pattern=$(find . -maxdepth 1 -type d ! -name '.' \
              | sed 's|^\./||' \
              | grep -vE "^($excluded_dirs)$" \
              | paste -sd'|' - \
              | awk '{ print "^(" $0 ")$" }')
          
            modules=$(echo "$changed_modules" | grep -E "$pattern" | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "modules=$modules" >> "$GITHUB_OUTPUT"
          fi

  build-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.modules != '[]' && needs.detect-changes.outputs.modules != '' }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-changes.outputs.modules) }}
      fail-fast: false  # 첫 번째 실패가 발생해도 나머지 작업들은 계속 진행됨
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
          fetch-depth: 0  # Shallow clones should be disabled

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and push image to Amazon ECR
        run: |
          REGION="ap-northeast-2"
          ECR_REPOSITORY="hidle-ecr"
          IMAGE_TAG=${{ matrix.module }}
          cp -r ten-private/.env.* . 2>/dev/null
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG -f ${{ matrix.module }}/Dockerfile . 
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

#  trigger-cd:
#    needs: build-push
#    if: ${{ success() }}
#    uses: ./.github/workflows/cd.yml

  deploy:
    needs:
      - detect-changes
      - build-push
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.modules != '[]' && needs.detect-changes.outputs.modules != '' }}
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-changes.outputs.modules) }}
      fail-fast: false  # 첫 번째 실패가 발생해도 나머지 작업들은 계속 진행됨
    steps:
      - name: Checkout with exact SHA
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
          fetch-depth: 0  # Shallow clones should be disabled

      - name: Generate deployment package
        id: ready
        run: |
          mkdir -p deploy/.platform/nginx/conf.d

          [ -f ten-private/.env.${{ matrix.module }} ] && cp ten-private/.env.${{ matrix.module }} deploy/.env.${{ matrix.module }} 2>/dev/null
          [ -f ${{ matrix.module }}/nginx/conf.d/proxy.conf ] && cp ${{ matrix.module }}/nginx/conf.d/proxy.conf deploy/.platform/nginx/conf.d/proxy.conf 2>/dev/null
      
          if [ -f ${{ matrix.module }}/docker-compose.yml ]; then
            cp ${{ matrix.module }}/docker-compose.yml deploy/docker-compose.yml
            echo "found_docker_compose=true" >> "$GITHUB_OUTPUT"
          else
            echo "found_docker_compose=false" >> "$GITHUB_OUTPUT"
          fi
          
          cd deploy && zip -r deploy.zip . && mv deploy.zip ..

      - name: Get current time
        if: steps.ready.outputs.found_docker_compose == 'true'
        uses: 1466587594/get-current-time@v2
        id: deploy-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      - name: Beanstalk Deploy
        if: steps.ready.outputs.found_docker_compose == 'true'
        uses: einaregilsson/beanstalk-deploy@v22
        continue-on-error: true
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: table-eat-now-${{ matrix.module }}-blue
          environment_name: Table-eat-now-${{ matrix.module }}-blue-env
          version_label: "github-action--${{ steps.deploy-time.outputs.formattedTime }}"
          region: ap-northeast-2
          deployment_package: deploy.zip
          wait_for_environment_recovery: 200