name: Create Jira issue

on:
  issues:
    types: [opened]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        actor: [hanjihoon03, hyezuu, je-pa, HanaHww2]

    steps:
      - name: Skip if not matching actor
        if: github.actor != matrix.actor
        run: echo "Not the actor. Skipping..." && exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set JIRA_USER_EMAIL
        run: |
          case "${{ matrix.actor }}" in
            hanjihoon03) echo "JIRA_USER_EMAIL=gkswlgns7653@gmail.com" >> $GITHUB_ENV ;;
            hyezuu) echo "JIRA_USER_EMAIL=duudu0704@gmail.com" >> $GITHUB_ENV ;;
            je-pa) echo "JIRA_USER_EMAIL=jieun0502@gmail.com" >> $GITHUB_ENV ;;
            HanaHww2) echo "JIRA_USER_EMAIL=hanahww2@gmail.com" >> $GITHUB_ENV ;;
            *) echo "Unknown actor"; exit 1 ;;
          esac

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: HD
          issuetype: Task
          summary: '${{ github.event.issue.title }}'
          description: '${{ github.event.issue.html_url }}'
