name: Create Jira issue

on:
  issues:
    types: [opened]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Jira credentials from actor
        id: set-jira-env
        run: |
          case "${{ github.actor }}" in
            hanjihoon03)
              echo "JIRA_USER_EMAIL=gkswlgns7653@gmail.com" >> $GITHUB_ENV
              echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN_HANJIHOON03 }}" >> $GITHUB_ENV
              ;;
            hyezuu)
              echo "JIRA_USER_EMAIL=duudu0704@gmail.com" >> $GITHUB_ENV
              echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN_HYEZUU }}" >> $GITHUB_ENV
              ;;
            je-pa)
              echo "JIRA_USER_EMAIL=jieun0502@gmail.com" >> $GITHUB_ENV
              echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN_JE_PA }}" >> $GITHUB_ENV
              ;;
            HanaHww2)
              echo "JIRA_USER_EMAIL=hanahww2@gmail.com" >> $GITHUB_ENV
              echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN_HANAHWW2 }}" >> $GITHUB_ENV
              ;;
            *)
              echo "❌ 이슈 작성자(${GITHUB_ACTOR})에 대한 Jira 정보가 없습니다."
              exit 1
              ;;
          esac

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ env.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: HD
          issuetype: Task
          summary: '${{ github.event.issue.title }}'
          description: '${{ github.event.issue.html_url }}'
